
#
# Docker image with the latest version of Ubuntu.
# With some basics installed.
#

FROM ubuntu:latest
ENV DEDIAN_FRONTEND=noninteractive

LABEL maintainer="D1al-T0ne"\
	email="d1al.t0ne@outlook.com"

# INSTALL THE BASICS
